development:
  #You can generate it with: rake secret 
  secret_key_base: "A secret here"
  secret_key_devise: "A secret here"
  
  #Facebook data
  app_id_facebook: "AppId"
  secret_key_facebook: "AppSecret"

test:
  #You can generate it with: rake secret 
  secret_key_base: "A secret here"
  secret_key_devise: "A secret here"
  
  #Facebook data
  app_id_facebook: "AppId"
  secret_key_facebook: "AppSecret"
  
production:
  #You can generate it with: rake secret 
  secret_key_base: "A secret here"
  secret_key_devise: "A secret here"
  
  #Facebook data
  app_id_facebook: "AppId"
  secret_key_facebook: "AppSecret"